### ISSUE TITLE
Update the Forum to latest version of phpBB (3.0.11)

### ISSUE THREAD

**Issue by xan2622** [OpenRA/OpenRAWeb#48]
Maybe it could be useful to update the Forum to the latest version of phpBB (currently 3.0.11) ?

**Comment by Mailaender** [comment]
I think I would prefer we switch to something modern like https://github.com/discourse/discourse.

**Comment by obrakmann** [comment]
Man, thanks for reminding me. Some weeks ago I read about the [dlang forum](http://forum.dlang.org) software, [DFeed](https://github.com/CyberShadow/DFeed), and wanted to tell you about it.

* It's web forum, mailing list and newsgroups gateway, all in one package, with one shared set of messages/posts.
* It's blazingly fast

I think it would be worse considering. Not sure how hard importing the old threads would be, though. Didn't find much documentation, unfortunately.

**Comment by x-a-n-a-x** [comment]
http://www.discourse.org/about/ seems really popular these days.
And a good thing : it features social logins (such as github).

**Comment by pchote** [comment]
I find the idea of "modern" websites that prioritize javascript effects over actual content to be offensive.  Discourse is one of the worse offenders in this category, and I would prefer almost any other solution over it.

**Comment by x-a-n-a-x** [comment]
I wouldn't say Discourse is full of flashy and eye-candy JavaScript effects. 
You can try it if you want : http://try.discourse.org/. 

It seems to have many useful and handy features , http://www.discourse.org/about/ is self-explanatory imo. 

And BTW, don't you like the idea to log-in with github? :-(  Many of our fans and contributors have one.

**Comment by Unit158** [comment]
Big :-1: for discourse here. It is absolute shit for perf on mobile.

**Comment by pchote** [comment]
I've created a converter that can port the forum database to phpBB 3.1, but we can't deploy it until we have an appropriate forum theme (#47).

**Comment by Mailaender** [comment]
Just use a default theme to deploy. https://github.com/OpenRA/OpenRAWeb/issues/47 is a another issue and the sub silver theme from your phpBB2 descended custom hacked board is the only really readable one anyway.

**Comment by Marionaise** [comment]
Hey,

saw your post @Facebook. Do you want to stay at phpBB or are you open to new things?

**Comment by pchote** [comment]
Potentially open to new things, so long as they fit the criteria:
* Free and open source.
* Low maintenance for both the board itself and any runtime it depends on.
* Supports importing the database of the existing forum without compromising topic descriptions or attachments - not willing to throw away 15 years of history as part of any move.
* Supports custom themes and other modifications (e.g. https://github.com/OpenRA/OpenRA/issues/2265).

Not a hard requirement, but strongly prefered:
* Implemented in python or php, as this is what most of our maintainers are fluent in.

**Comment by pchote** [comment]
With the GDPR coming into force today, the lack of maintenance of the old forum is no longer just sad, it is now criminal.  It is not feasible to retrofit the old forum software to comply with the requirements for data export or deletion, and I do not have the time / interests / technical expertise to lead the development on or actively project manage a replacement.  We will require help from members of the wider OpenRA community to get this back on track and (hopefully) minimize the amount of downtime incurred.

For the short term I have disabled access to the forum using the generic board-disable feature.  When time permits I plan to properly decommission the forum and database, replacing it with a page explaining the situation and directing readers to this issue in order to rally manpower for the next step.

Newer forum software have (or, if not, certainly will) added features or community mods to support proper data management.  We need to be able to finish development of the stalled http://forum2.openra.net project, on OpenRA server infrastructure, and make sure that it complies with the new regulations.  When that is ready we can migrate the posts from the OpenRA forums and the subset of users who were active during the "OpenRA era" to the new board.

Sleipnir's Stuff holds a lot of history from the last 16 years, and while it is sad to finally shut it down it has been a long time coming.  Most of the content has been archived in a read-only mode for 3+ years to reduce the impact of human spammers.  It had a good run, and with the death of Generals modding and the centralization of the 2.5D game modding around PPM I feel that we can retire this content without causing a significant loss to the community.  If I'm wrong and there is an unexpected demand to keep this available then it would not be particularly difficult to scrub personal data (emails, ip addresses, etc) and then keep this available somewhere separate to OpenRA.

**Comment by pchote** [comment]
Done.  See https://forum.openra.net/viewtopic.php?f=81&p=307686#p307683
