### ISSUE TITLE
OpenRA Website Update Proposal

### ISSUE THREAD

**Issue by Fauntleroy** [OpenRA/OpenRAWeb#493]
Similar to https://github.com/OpenRA/OpenRAWeb/issues/491, I have a vision for and update to the OpenRA website I'd like to share.

| Desktop | Mobile |
| ----- | ----- |
|<img width="1398" alt="Screen Shot 2020-06-23 at 10 39 36 AM" src="https://user-images.githubusercontent.com/507047/85437383-59a87200-b53f-11ea-8295-0a580371c03b.png"> | <img width="545" alt="Screen Shot 2020-06-23 at 10 54 51 AM" src="https://user-images.githubusercontent.com/507047/85437790-04b92b80-b540-11ea-8193-602ff52198d7.png"> |

There is an incomplete live demo here: https://openra.kempf.dev/

## Motivation

After looking into the current state the website and speaking briefly with the team in Discord, I came up with some ideas on how to improve it. My goal is to maximize the quality, speed, and developer experience of the OpenRA website.

### Visual Identity

I created a design to emphasize "open" and "modern" nature of the OpenRA project. Here's how:

- The logo and headings use [Jost](https://indestructibletype.com/Jost.html), a **free and open source typeface** with sharp edges and smooth circular forms that mesh well with the points of the star and the curves of the sickle in the logo.
- The body and smaller headings use [Inter](https://rsms.me/inter/), a **free and open source typeface** that is versatile and easy to read.
- Visual noise is reduced by using vector shapes and simple, bright colors. Screenshots (showing OpenRA itself) easily become the focus.
- Visual hierarchy of the page has been tuned to ensure that users progress through content smoothly and easily.
- All of the games on offer are represented, though Red Alert (being the namesake) naturally shows up first.

### Mobile Compatibility

The website was designed with mobile devices and tablets in mind. The simple layout is versatile and easily adjusts to work with devices of any size.

| Tablet | Mobile |
| ----- | ----- |
| <img width="871" alt="Screen Shot 2020-06-23 at 11 17 45 AM" src="https://user-images.githubusercontent.com/507047/85440818-49929180-b543-11ea-986d-4f9fc40a52a1.png"> | <img width="545" alt="Screen Shot 2020-06-23 at 10 54 51 AM" src="https://user-images.githubusercontent.com/507047/85437790-04b92b80-b540-11ea-8193-602ff52198d7.png"> |

### Simplicity

I built the website to be a simple as possible while still feeling modern. This helps bridge the gap between the time of the classics, where websites were just simple html pages—and today's world.

- No JS frameworks. This simply uses [jQuery](https://jquery.com/) like the current website.
- Works without JS. Even without JS enabled the website is still functional.
- Extremely fast and efficient. This implementation is well optimized and scores well in Lighthouse (Note: "Best Practices" lost a couple points for something that is actually an optimization): <img width="428" alt="image" src="https://user-images.githubusercontent.com/507047/85441505-0d136580-b544-11ea-8c7b-3d3035b739b2.png">
- Uses a static site generator ([Metalsmith](https://metalsmith.io/))

### Focus on the Games

The carousel on the front page is considerably larger than the one on the current website. This draws attention to the mods/games on offer, and helps new visitors understand the nature of the project (as the carousel goes through the mods/games). This will serve as an entry point to the "About" page, and will auto scroll to whichever game they clicked on.

## Closing

Ultimately my motivation is to build a website which works best for both the project and the team. I want the website to be the best it can be while being simple and easy to manage for the team. I am also interested in sticking around and maintaining the quality of the web related parts of the project moving forward.

**Comment by pchote** [comment]
I think this looks great, mostly. Something about the background image rubs me the wrong way, but I don't have any specific suggestions on how to change it. If we move forward with this IMO we should put some effort into obtaining new images (or maybe videos?) for the image carousel.

I would be interested in seeing your visions for the other pages too! An updated player stats page could could perhaps tie in with the old plan of surfacing some of the information from the system info database (fraction of people on windows/mac/linux, fractions of played mods, etc).

**Comment by Fauntleroy** [comment]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/507047/85445155-f242f000-b547-11ea-9629-109f28fb2a44.png">

Do you mean this image? I'd love to keep it around (it's inspired by the background on the current website, harkens back to the good ol' days where every website had a silly tiling background, and helps reinforce the idea of OpenRA being pan-game), so let me know if you can figure out what bothers you about it! Also, I'm planning on vectorizing and adding the 3 faction logos from Dune 2000 if my proposal is accepted.

I'll be working through the other pages now that I've got the website building through Metalsmith. Expect to see those pages within the next couple days. As for **player stats**, I'm interested to know what your wants/dreams are around that. Would you like to surface current player information on the front page (like [CNCnet](https://cncnet.org/)?). Just let me know what you're looking for, anything's on the table.

Also, forgot to drop a link to my working repo: https://github.com/Fauntleroy/openra-web . When complete I can easily make it into a pull request for this repo, or whatever works best for the project.

**Comment by matjaeck** [comment]
My first impression is very positive. Noted a couple of things (mobile):
- drawer should lock page scrolling and maybe have a different background to be distinguishable from the content behind
- footer looks a bit chaotic, consider moving legal and copyright to its own row below links and make the section have only one column 
- anchor text for social links needs alignment or IMO remove the text next to the logos 
- consider removing the border of the news section for mobile
- consider displaying the whole comment feed below the article (nvm if it is the plan anyway)
- Colors accessibility: as a colorblind person with protanopia I can confirm that red on black works, although being hard to look at for a longer time in case of text. I obviously liked the golden highlight on the currentsite better, but that just as a sidenote
- not a fan of the red OS logos but that coukd be because of ^
- great job so far, hope to see more :)
-

**Comment by Fauntleroy** [comment]
I have updated my version of the site with all of the news posts from the current website. I've replaced Metalsmith with [Jekyll](https://jekyllrb.com/) as discussed in discord, and made sure all the permalinks match up. Some notes:
- I replaced all of the YouTube embeds with the much lighter `<lite-youtube>` embed. Functions the same as you would expect.
- I noticed there are some green boxes (see: https://openra.kempf.dev/news/playtest-20200426) hardcoded into the markdown of the news posts. Unless this is hardcoded to work with feed readers or the like, I'd prefer to make this a re-usable element.

### News List (https://openra.kempf.dev/news/)

| Desktop | Mobile |
| --- | --- |
| <img width="1218" alt="Screen Shot 2020-06-25 at 7 57 39 AM" src="https://user-images.githubusercontent.com/507047/85745620-b1b7b380-b6ba-11ea-93e6-1980f9aaa5e3.png"> | <img width="545" alt="Screen Shot 2020-06-25 at 8 01 32 AM" src="https://user-images.githubusercontent.com/507047/85745812-d57af980-b6ba-11ea-8f8f-e0121a49a7ad.png"> |

### News Detail (https://openra.kempf.dev/news/release-20200503)

| Desktop | Mobile |
| --- | --- |
| <img width="1193" alt="Screen Shot 2020-06-25 at 8 00 16 AM" src="https://user-images.githubusercontent.com/507047/85745883-e592d900-b6ba-11ea-93ac-b402322716a1.png"> | <img width="545" alt="Screen Shot 2020-06-25 at 8 01 38 AM" src="https://user-images.githubusercontent.com/507047/85745988-fa6f6c80-b6ba-11ea-9f94-62435cf70c07.png"> |
| <img width="1193" alt="Screen Shot 2020-06-25 at 8 00 22 AM" src="https://user-images.githubusercontent.com/507047/85745912-ec215080-b6ba-11ea-9d25-655c2fda2a91.png"> | <img width="545" alt="Screen Shot 2020-06-25 at 8 01 44 AM" src="https://user-images.githubusercontent.com/507047/85746170-1d018580-b6bb-11ea-898b-52be535fc304.png"> |

@matjaeck I've taken a look at the things you mentioned, and taken care of a few of them. I used a protanopia simulator to take a look at the site and I can completely understand what you're talking about. I'm not sure how much I can do since, no matter how I look at it, the primary color should be red (Open Red Alert and all). I'll keep working to ensure that the site is accessible, and will refine the elements of the front page (github, discord links & OS icons) closer to the end of this update.

@pchote How are posts authored? I see that they're all markdown files, but there's also a LOT of html going into them. Are they manually written and added to the repo?

Up next: further refinements and content pages.

**Comment by IceReaper** [comment]
>>> No JS frameworks. This simply uses jQuery like the current website.
Thats easy to get rid of actualy :-P
If you want contact me, did professional web development for over 10 years, so im willing to help out here if you need a hand.

**Comment by dragunoff** [comment]
I like the overall direction here. I have some suggestions regarding the visual design.

#### Link styles
I think red doesn't work great for text and on black doesn't have sufficient contrast so it's not very readable even for people without visual impairments. I'd suggest using a golden color for the links - this really pops up on dark backgrounds and is still fairly distinguishable from regular text. It is also present in the logo.

I'd suggest not using bold links in body text. It's OK in lists or other parts of the site but in the main content area bold should be used only for emphasis.

Red works fine for buttons though.

![Screenshot_2020-06-25 OpenRA - Open Source Command Conquer, Red Alert, and more(2)](https://user-images.githubusercontent.com/1355810/85774903-f3cb0e80-b727-11ea-8304-852ef90cbfc8.png)

![Screenshot_2020-06-25 OpenRA - Open Source Command Conquer, Red Alert, and more](https://user-images.githubusercontent.com/1355810/85775837-d2b6ed80-b728-11ea-872a-7754de4b83e3.png)

#### Footer
The footer seems a little busy. It repeats the header menu and the logo in the same style as the header. I'd suggest using a monochrome logo (maybe also smaller in size) in the footer and perhaps getting rid of the main menu duplicate. Here's a quick mockup with a grayscale logo (a proper monochrome version should be created):

![Screenshot_2020-06-25 OpenRA - Open Source Command Conquer, Red Alert, and more(1)](https://user-images.githubusercontent.com/1355810/85775283-4f959780-b728-11ea-891a-c83db552b2b9.png)

### Responsive menu
I suggest using a drawer style menu for the small screen sizes. Users are familiar with this interaction paradigm and a stacked list is easy to use on touch devices:

![Screenshot_2020-06-25 OpenRA - Open Source Command Conquer, Red Alert, and more(4)](https://user-images.githubusercontent.com/1355810/85775537-8a97cb00-b728-11ea-981e-a87d4a2116e8.png)

I will have some comments on the code side of things but more on that later. Keep up the good work 👍

**Comment by Fauntleroy** [comment]
I've added a couple of new pages to the website:

### Server Browser (https://openra.kempf.dev/games)

| Desktop | Mobile |
| --- | --- |
| ![Screen Shot 2020-06-29 at 10 35 41 PM](https://user-images.githubusercontent.com/507047/86088085-7de1e280-ba5a-11ea-997a-3c50d80f9477.png) | ![Screen Shot 2020-06-29 at 10 39 11 PM](https://user-images.githubusercontent.com/507047/86088198-b386cb80-ba5a-11ea-96ae-2526f2a2d6de.png) |

First up is the Server Browser. I haven't written anything [this complex](https://github.com/Fauntleroy/openra-web/blob/master/docs/scripts/server-browser.js) without a framework in quite some time, but I made sure it's rock solid (and avoids any possible XSS from weird mod names). Servers are grouped by mod, you can filter by status, and you can sort by column. There are join buttons and lock icons for private games. I'll probably come back to this and add a couple more fun features at a later date.

As for map data... I omitted it because the requests for map data can become super heavy, especially if the "empty" filter is checked. If the response from `master.openra.net` included the map _name_, this could be easily avoided. I think that's the right approach towards this issue, if it's possible.

### Player Statistics (https://openra.kempf.dev/players)

| Desktop | Mobile |
| --- | --- |
| ![Screen Shot 2020-06-29 at 10 36 17 PM](https://user-images.githubusercontent.com/507047/86089168-93580c00-ba5c-11ea-9bad-c64db6ca7ee7.png) | ![Screen Shot 2020-06-29 at 10 39 27 PM](https://user-images.githubusercontent.com/507047/86089215-a7037280-ba5c-11ea-9498-568657348db7.png) |

The Player Stats page isn't really any different than the existing one. Some elements were moved around, and some styles were changed, but it's basically the same.

I thought this might be a good candidate for optimization, as [flot](https://www.flotcharts.org/) and the supporting plugins are all quite heavy, but flot is the only game in town when it comes to presenting `.rrd` data in a browser. A lighter, more easily style-able library could be used, but changes to `activity.openra.net` would need to be made, and that's out of scope.

#### The Background Image

<img width="555" alt="image" src="https://user-images.githubusercontent.com/507047/86089629-6ce6a080-ba5d-11ea-9ae8-2b39a16fbfaf.png">

The background image has been changed from strokes to fills. Personally, I lean more towards the strokes, but this works well.

#### The Slide Out Menu

<img width="367" alt="image" src="https://user-images.githubusercontent.com/507047/86091157-42e2ad80-ba60-11ea-8e17-c2975e30f57f.png">

Links are once again stacked. I'm not too keen on making the menu stretch to fit the height of the window, as this interface is designed to smoothly adjust to any window size (not just hitting precise device breakpoints).

#### Throwback Hover / Focus Effect

![button-highlight](https://user-images.githubusercontent.com/507047/86091533-eb910d00-ba60-11ea-8042-1fd8a27f564e.gif)

I spent some time figuring out how to create an effect similar to the highlight cursor in Red Alert. The CSS is a bit intense for this one, so let me know if it isn't working for you.

#### Fonts and jQuery are Locally Hosted

I added the fonts and jQuery as static files. No more extra requests to Google / jQuery!

Thanks for all the replies and feedback, y'all. Even if I don't respond directly to your feedback, do know that I am reading everything and keeping it in mind while I work on this. Up next are the rest of the site's pages!

**Comment by dragunoff** [comment]
The new link style looks better 👍 
I think the background with solid logos works well because it's less busy 👍 

Here are some notes and suggestions in no particular order:

1. These list items seem too close together, I'd suggest adding some margin between them:
![Screenshot_2020-06-30 OpenRA - Open Source Command Conquer, Red Alert, and more(2)](https://user-images.githubusercontent.com/1355810/86118206-0b641780-bad9-11ea-93a6-ba9b46181359.png)

1. Image captions could have a different style to distinguish them from the main text. The current markup is not suited for that so there is also an opportunity to properly mark them as `<figure>`:
![Screenshot_2020-06-30 OpenRA - Open Source Command Conquer, Red Alert, and more(3)](https://user-images.githubusercontent.com/1355810/86118213-0ef79e80-bad9-11ea-9048-2097cfb27893.png)

1. The link hover effect perhaps should not be applied to inline links as it doesn't really work with line breaks:
![Screenshot_2020-06-30 OpenRA - Open Source Command Conquer, Red Alert, and more](https://user-images.githubusercontent.com/1355810/86118223-161eac80-bad9-11ea-9e79-024d21f8da2a.png)

1. Such links should have a `display: inline-block` so the hover effect can wrap the whole image:
![Screenshot_2020-06-30 OpenRA - Open Source Command Conquer, Red Alert, and more(1)](https://user-images.githubusercontent.com/1355810/86118216-128b2580-bad9-11ea-994c-a716b06d9baa.png)

1. The hover effect should be disabled for users that have enabled "reduced motion" (see https://developer.mozilla.org/bg/docs/Web/CSS/@media/prefers-reduced-motion).

**Comment by dragunoff** [comment]
On the code side of things, here are some suggestions:

1. Before a ton of CSS has been written I highly recommend that we use SCSS to break `index.css` into partials (Jekyll supports SCSS out of the box). I see that you're using BEM naming convention which is great. I suggest you break each BEM block into it's own SCSS partial file and also break the base and utility styles into partials. I'd also recommend to follow the ITCSS convention (see https://www.xfive.co/blog/itcss-scalable-maintainable-css-architecture/) for structuring and layering the partials.
1. I suggest keeping media queries in context - i.e. near the selectors that they affect. SCSS makes that easier because it allows media queries to be nested in the selector. This makes sure all the styles relevant to a block are in the same place. For example:
```scss
.u-centered-content {
  max-width: 1100px;
  margin: 0 auto;
  padding: 0 2.5rem;

  @media screen and (max-width: 680px) {
    padding-left: 1rem;
    padding-right: 1rem;
  }

  @media screen and (max-width: 1000px) {
    padding-left: 2rem;
    padding-right: 2rem;
  }
}
```
3. SCSS also allows selectors for BEM to be written like this:
```scss
.site-header {

  &__main {}

  &__menu-toggle {}

  &__logo {}
}
```

**Comment by Fauntleroy** [comment]
@dragunoff thanks for the great feedback! I've gone ahead and addressed a few of the things you brought up:

- I've moved the images and videos of the last couple posts into `<figure>`s with `<figcaption>`s. The style is only a little different, but it does clean up the code in the post quite a bit.
- The hover effect for the OS logos has been fixed
- Major motions, such as the carousel effects and the link hover effect, have been disabled for users who prefer less motion.
- I've begun moving the CSS to SCSS. Right now it's just rudimentary file splitting, nesting, and media queries, but I'll get to work cleaning up the rest soon.

These changes are live on https://openra.kempf.dev

**Comment by Fauntleroy** [comment]
Hey y'all, it's me again. This time we've got two new content pages; **Download** and **Community**.

### Download (https://openra.kempf.dev/download)

| Desktop | Mobile |
| --- | --- |
| <img width="1234" alt="Screen Shot 2020-07-06 at 9 32 21 AM" src="https://user-images.githubusercontent.com/507047/86617557-3ed8f300-bf6c-11ea-87ec-6270112d1dab.png"> | <img width="545" alt="Screen Shot 2020-07-06 at 9 34 58 AM" src="https://user-images.githubusercontent.com/507047/86617595-50ba9600-bf6c-11ea-8b82-cb33c2b495fc.png">  |

This is basically the same as the existing download page, with a different layout. There are two radio button groups which let you toggle the various operating systems and builds. Through great emotional toil I learned enough Ruby to [generate the content for this page via the GitHub API](https://github.com/Fauntleroy/openra-web/blob/master/scripts/generate-release-data.rb). If a playtest id is added, the script will add a `playtest` key and the playtest option will be un-disabled.

### Community (https://openra.kempf.dev/community)

| Desktop | Mobile |
| --- | --- |
| <img width="1234" alt="Screen Shot 2020-07-06 at 9 32 49 AM" src="https://user-images.githubusercontent.com/507047/86618098-2c12ee00-bf6d-11ea-9eb3-0336b212f357.png"> | <img width="545" alt="Screen Shot 2020-07-06 at 9 34 44 AM" src="https://user-images.githubusercontent.com/507047/86618116-3634ec80-bf6d-11ea-94e6-5ee1dfbe139e.png"> |

The current community page is a bit sparse, while the OpenRA community itself is... expansive. Therefore, I rebuilt this page from the ground up to _try_ and elucidate on just how many ways there are to participate in the OpenRA community. If there's anything important I missed, let me know.

Note: I intentionally left out the webIRC link for Freenode since the Discord is much more active, and better serves those who do not use IRC already.

### OpenGraph Tags

I went ahead and filled out the [OpenGraph](https://ogp.me/) tags as simply as possible. This means that links posted to services like Facebook, Twitter, Slack, Discord, etc will "unfurl" and display some extra information. These can be customized per-page if necessary (but they are not at this time).

| Slack | Twitter |
| --- | --- |
| <img width="663" alt="image" src="https://user-images.githubusercontent.com/507047/86618539-f6223980-bf6d-11ea-95cd-cb8ee6df2191.png"> | <img width="519" alt="image" src="https://user-images.githubusercontent.com/507047/86618634-1b16ac80-bf6e-11ea-9c08-ffa192eeb77b.png"> |

### Remaining Work

This implementation is almost complete! There are only a few pages remaining, then it's all down to detail work and ensuring feature-completion. Here's what I'll be working on next:

- About page
- Legal page
- 404 page
- Sitemap (is this important to y'all?)
- Ensure RSS feeds work
- Ensure public URLs in use by other things (like the "game news" in OpenRA) are there
- Experiment with small videos in front page carousel
- Google Analytics and other third party JS integration
- Final cross browser check
- Final lighthouse score check
- Documentation

If there's anything else you have in mind, let me know.

**Comment by dragunoff** [comment]
This looks promising 👍 I have some comments on the visual parts, again in no particular order:

1. The selected radio button does not differ enough from the unselected ones. There should be starker visual contrast so the user can see at a glance which is the selected option.
![Screenshot_2020-07-07 OpenRA](https://user-images.githubusercontent.com/1355810/86816861-03821580-c08d-11ea-93f9-16bd0c41233d.png)

1. I think that hiding the playtest behind a radio button toggle is not good because it decreases the visibility of the playtest and this is very much not desired for a playtest. I think the current site does this better. You can look at how other games/products do that, I don't have any examples of the top of my head.
![Screenshot_2020-07-07 OpenRA(1)](https://user-images.githubusercontent.com/1355810/86816857-03821580-c08d-11ea-91e9-86a701964ade.png)

1. I think the headings could use some more margin (or a variation in the style). Since the font size is similar these headings almost reads like one sentence.
![Screenshot_2020-07-07 OpenRA(2)](https://user-images.githubusercontent.com/1355810/86816852-0250e880-c08d-11ea-9eae-26fe8d0464e7.png)

1. Having the download links and info by the side and wrapped in a box makes them look a bit like an aside. As if that block doesn't have a direct relation to the main content in the left column. I'd suggest to keep it all in one column and going from most to least important information:
![image](https://user-images.githubusercontent.com/1355810/86818410-067e0580-c08f-11ea-902b-ae4b61fb7abf.png)

**Comment by dragunoff** [comment]
On the code side of things:

1. Please be strict with BEM - there is little value in applying a convention only partially. The main idea behind BEM is very simple and is well documented: http://getbem.com/. Of course you can choose not to follow a convention or follow a different one.

1. I'd suggest you follow a stricter convention with regards to splitting SCSS into partials and that is: **one block (component) per file** (this doesn't pertain to utility, type or other global and generic styles). Because again there is little value in splitting because the partials keep growing and we end up with long sheets of SCSS that are hard to debug and maintain.

1. Atomic CSS has been seeing more and more use and gaining more proponents so this is also an avenue to explore. But for a small project like this it may not be too appropriate. I'd stick to styling components with some utility classes sprinkled over.

1. You can create custom radio button styles by using this technique. That way you won't have to rely on the native radio controls which vary wildly between browser and OS and you can hook to the browser native pseudo-classes:
```html
<input type="radio" id="radio-button" class="radio" /><label for="radio-button">Turn on the radio</label>
```
```scss
.radio {
  // hide the input (you could use another, more accessibility friendly technique to hide it visually)
   display: none;

  + label {
    
    &::before, &::after {
      // use pseudo elements to create the custom radio input
    }

  &:selected + label {

    &::before, &::after {
      // change the style of the custom input when the real one is selected
    }
  }
}
```

**Comment by Fauntleroy** [comment]
Due to limitations with the previous design, I went through a longer, iterative design process to come up with the current design. It's quite close to the original, but with a few improvements:

- A simple grid based design
- Center aligned content with support for a variety of sizes
- A great deal of refinement and polish on various interface elements
- Performance improvements

### Home (https://openra.kempf.dev/)

| Desktop | Mobile |
| --- | --- |
| <img width="1652" alt="Screen Shot 2020-07-26 at 5 47 06 PM" src="https://user-images.githubusercontent.com/507047/88494179-a54ca200-cf69-11ea-9358-caa6f1600531.png"> | <img width="559" alt="Screen Shot 2020-07-26 at 5 52 15 PM" src="https://user-images.githubusercontent.com/507047/88494203-bbf2f900-cf69-11ea-8518-807759365862.png"> |

The home page has seen a serious optimization pass, along with some design updates. It's basically the same as it was before, but more refined.

### News Archive (https://openra.kempf.dev/news/)

| Desktop | Mobile |
| --- | --- |
|  <img width="1652" alt="Screen Shot 2020-07-26 at 6 01 51 PM" src="https://user-images.githubusercontent.com/507047/88494282-40de1280-cf6a-11ea-8384-86b23f6a77ec.png"> | <img width="559" alt="Screen Shot 2020-07-26 at 6 02 46 PM" src="https://user-images.githubusercontent.com/507047/88494309-57846980-cf6a-11ea-819a-e1bae892eb9c.png"> |

The news archive is largely the same as before, but sorted by year.

### About (https://openra.kempf.dev/about/)

| Desktop | Mobile |
| --- | --- |
| <img width="1652" alt="Screen Shot 2020-07-26 at 5 47 28 PM" src="https://user-images.githubusercontent.com/507047/88494351-931f3380-cf6a-11ea-9fef-c0fc1adc098b.png"> | <img width="559" alt="Screen Shot 2020-07-26 at 5 52 28 PM" src="https://user-images.githubusercontent.com/507047/88494369-ae8a3e80-cf6a-11ea-953f-5cc93448fa99.png"> |

The about page is finally here! This is simply an adaptation of the existing about page, but I've made various edits here and there. Still working on a way to handle the screenshots on mobile.

### Download (https://openra.kempf.dev/download/)

| Desktop | Mobile |
| --- | --- |
| <img width="1652" alt="Screen Shot 2020-07-26 at 5 47 57 PM" src="https://user-images.githubusercontent.com/507047/88494457-117bd580-cf6b-11ea-9b4b-5133158477f8.png"> | <img width="559" alt="Screen Shot 2020-07-26 at 5 52 38 PM" src="https://user-images.githubusercontent.com/507047/88494484-26586900-cf6b-11ea-9f49-4d03e081b4e1.png"> |

The download page has been moved around according to user feedback. The OS selector is big and evident, and download instructions include buttons for both release and playtest. You can link directly to one set of instructions using a hash link: https://openra.kempf.dev/download#free-bsd

### Server Browser (https://openra.kempf.dev/games/)

| Desktop | Mobile |
| --- | --- |
| <img width="1652" alt="Screen Shot 2020-07-26 at 5 48 03 PM" src="https://user-images.githubusercontent.com/507047/88494560-72a3a900-cf6b-11ea-9f36-fe4c8fe15b6d.png"> | <img width="559" alt="Screen Shot 2020-07-26 at 5 52 47 PM" src="https://user-images.githubusercontent.com/507047/88494580-8c44f080-cf6b-11ea-8a85-d64bbbe2b1b5.png"> |

The server browser is largely unchanged, but has seen some polish.

### Community (https://openra.kempf.dev/community/)

| Desktop | Mobile |
| --- | --- |
| <img width="1652" alt="Screen Shot 2020-07-26 at 5 48 07 PM" src="https://user-images.githubusercontent.com/507047/88494633-c8785100-cf6b-11ea-9880-a4563400ecf3.png"> | <img width="559" alt="Screen Shot 2020-07-26 at 5 52 53 PM" src="https://user-images.githubusercontent.com/507047/88494654-dc23b780-cf6b-11ea-8f7c-109ea4c82c9f.png"> |

The community page has seen a small layout change.

### Legal (https://openra.kempf.dev/legal/)

| Desktop | Mobile |
| --- | --- |
| <img width="1652" alt="Screen Shot 2020-07-26 at 5 53 03 PM" src="https://user-images.githubusercontent.com/507047/88494764-4ccad400-cf6c-11ea-93b4-96a270090270.png">  |  <img width="559" alt="Screen Shot 2020-07-26 at 5 53 14 PM" src="https://user-images.githubusercontent.com/507047/88494784-653aee80-cf6c-11ea-91d8-fc025c5d495c.png"> |

I've added the legal page. I thought it would be nice to include the license on the same page, but if it's a problem it is quite simple to move it back.

### 404 (https://openra.kempf.dev/cnc-5/)

| Desktop | Mobile |
| --- | --- |
| <img width="1652" alt="Screen Shot 2020-07-26 at 5 53 41 PM" src="https://user-images.githubusercontent.com/507047/88494898-df6b7300-cf6c-11ea-8781-49fd24c4b1f0.png"> | <img width="559" alt="Screen Shot 2020-07-26 at 5 53 34 PM" src="https://user-images.githubusercontent.com/507047/88494903-f14d1600-cf6c-11ea-8825-9399c2f11793.png"> |

There's a 404 page! I thought it would be fun to make a Windows 95 style dialog box, so I did. I'd love to include some "blooper" videos or screenshots to pad out the page and keep it interesting.

### Alright, what next?

There are a few things here and there for me to complete on the website, but I could use some help finding/making screenshots and videos to use in the carousel/about page. As always, let me know your feedback!

**Comment by kingo55** [comment]
"404 - Silos needed" or even "404 - Unit lost" springs to mind...

<img width="1059" alt="Screen Shot 2020-07-27 at 13 17 21" src="https://user-images.githubusercontent.com/2361388/88500265-83a3f700-d00b-11ea-9960-ff384cbec891.png">

**Comment by dragunoff** [comment]
@Fauntleroy The new design direction is great, I think you're on the right path. I have some suggestions design-wise, mostly minor things:

1. It would be good to always include the separator between sections of different widths to avoid such glitches and to justify the width change:
![Screenshot_2020-08-14 OpenRA](https://user-images.githubusercontent.com/1355810/90250319-8cd2f780-de44-11ea-920b-34f11a29e087.png)

1. IMO it may be better to stick to a single width for sections and avoid changing the width altogether. The separator can stay but to simplify things keep all sections at the same width. 
![Screenshot_2020-08-14 OpenRA(4)](https://user-images.githubusercontent.com/1355810/90250441-b429c480-de44-11ea-80d4-d16f87382d49.png)

1. Checkboxes and radios don't have a focus state, consider using the technique I outlined in https://github.com/OpenRA/OpenRAWeb/issues/493#issuecomment-655020065:
![Screenshot_2020-08-14 OpenRA(2)](https://user-images.githubusercontent.com/1355810/90250880-7da07980-de45-11ea-985f-bdbd2ff159c3.png)
![Screenshot_2020-08-14 OpenRA(1)](https://user-images.githubusercontent.com/1355810/90250928-927d0d00-de45-11ea-9c56-699c927a0570.png)

1. Perhaps these two links should have an external link indicator:
![Screenshot_2020-08-14 OpenRA(3)](https://user-images.githubusercontent.com/1355810/90251022-c0625180-de45-11ea-94ef-960716bbf75e.png)

1. I'd suggest keeping the selection effect only in the header and footer. It has issues with buttons (due to the combined animation effect) and inline links spanning multiple lines. Having it in the header/footer would still provide significant aesthetic value.
![Screenshot_2020-08-14 OpenRA(5)](https://user-images.githubusercontent.com/1355810/90251146-ee479600-de45-11ea-9b6c-725ed7faff39.png)

**Comment by teinarss** [comment]
Looks awesome!

Just one thing, it would look better IMO if the content width was kept the same.
![image](https://user-images.githubusercontent.com/19173272/91605093-33a0b300-e970-11ea-9f31-6fd857c0a816.png)

**Comment by pchote** [comment]
I second the request to keep a fixed content width in the background.
I sadly think that we are unlikely to find people willing to contribute a selection of good images for the carousel, so I suggest removing that and redesigning that part of the home page to be more like the current website. This would get us significantly closer to a releaseable form.

**Comment by Fauntleroy** [comment]
- @pchote I've spent some time recording a "demo" video of my own to place in the carousel. If my attempt is good enough, I'll go ahead and make a few more for the other games (but maybe not tibsun?). Please take a look and let me know what you think: https://openra.kempf.dev/
- the stripes on the left and right sides of the content are now always lined up, due to popular demand
- I've modified the header slightly and made it fixed
- <figure> + <figcaption> have been modified to better work inside news posts
- Spacing has been modified across the board
- I've added an affordance for spectators to the games list. It is similar to the one on the current games list: https://openra.kempf.dev/games

**Comment by pchote** [comment]
Looks good to me 👍 I agree that we shouldn't show tibsun there until we have a public release for it.
It would be great if we could try and deploy this with the next release (likely in late january / early feb), so i'll aim to start going through the pages with a finer toothed comb and make suggestions.

**Comment by pchote** [comment]
I have started filing issues on https://github.com/Fauntleroy/openra-web to cover my last nits (and maybe PRs once if I get on top of the learning curve).

If anyone else has any major issues with this design can you please speak up now?

**Comment by dragunoff** [comment]
I quite like the design. Maybe there are a few very minor nits but no blockers.

I'm not too fond of the CSS though 🤔 For better maintainability I think it needs a more logical organization, better component breakdown, maybe some more utility classes and stricter adherence to the BEM naming convention. Addressing all of that can take a while so I don't know whether we should be dealing with it now (or at all).

**Comment by abcdefg30** [comment]
> If anyone has any major issues with this design can you please speak up now?

One thing I noticed is that the "Resources" link in the menu/nav bar probably wants to be renamed to "Map Center" or something like that. Just "Resources" imo doesn't really convey that it just links to maps. (It could be basically anything just by the name, game guides, mod files, ...)

**Comment by matjaeck** [comment]
>  If anyone has any major issues with this design can you please speak up now?

The style of the top headings reminds of MS Word Wordart: 
![1335313](https://user-images.githubusercontent.com/59416324/103142772-caf0f980-4709-11eb-9f76-3c72136c2c9d.png)

(First in third row)

**Comment by pchote** [comment]
I have made some final minor wording tweaks and have implemented the release automation, so this is now ready to go as far as i'm concerned. This is live at https://pchote.github.io/openra.github.io/, and when we are ready we can move the repo into the OpenRA org and switch the deployment config to OpenRA/openra.github.io.

I would like to deploy this along side the new release hopefully this coming weekend, so can we please some go/no-go confirmations from @OpenRA/core?

**Comment by Mailaender** [comment]
I like it a lot. A minor bug: when searching with Google Chrome the font is doubled/distorted:

![image](https://user-images.githubusercontent.com/756669/109421364-422b5e00-79d7-11eb-92ac-1ebb30ce14a3.png)

**Comment by Mailaender** [comment]
and https://www.gamereplays.org/openra/ is missing

**Comment by Mailaender** [comment]
https://pchote.github.io/openra.github.io/legal#license is missing a space:

![image](https://user-images.githubusercontent.com/756669/109421506-e7463680-79d7-11eb-9ee2-187e94a26434.png)

Also, that EA modding FAQ allows modding, but not redistribution. It does not cover that case at all. It should be mentioned in another context.

**Comment by dragunoff** [comment]
> I like it a lot. A minor bug: when searching with Google Chrome the font is doubled/distorted:
> 

This is because the text has a shadow applied with CSS. I don't think there is a way to remove that for search highlights because there is no selector for that in CSS. So this is a wontfix.

I noticed that clicking on the slider buttons causes the page scroll to jump to the top. I guess the intention was for the user to see the changing text above the slideshow but ultimately it feels jarring.
![image](https://user-images.githubusercontent.com/1355810/109480983-e15a5f00-7a84-11eb-9ec4-c1ba2f96c1d9.png)

The menu in the footer has an underline on hover that together with the selection box gives it a cluttered look. I thnk the underline can be removed.
![image](https://user-images.githubusercontent.com/1355810/109483954-8296e480-7a88-11eb-9a1b-35fad3e524de.png)
![image](https://user-images.githubusercontent.com/1355810/109484068-a8bc8480-7a88-11eb-9ae4-cbf167b6176d.png)

I think the main menu should highlight the current page (e.g. highlight "News" menu item on "News" page).
![image](https://user-images.githubusercontent.com/1355810/109484214-d6093280-7a88-11eb-8640-65fc9968c7af.png)

These are all minor nits. Altogether the site is great :+1: :zap:

**Comment by pchote** [comment]
and... done! https://github.com/OpenRA/OpenRAWebsiteV3/
